permalink:           pretty

# Setup
title:               Aaron Stevens' Blog
description:         ''
url:                 https://bheklilr.github.io
baseurl:             http://localhost:4000
paginate:            5

# About/contact
author:
  name:              Aaron Stevens
  url:               https://bheklilr.github.io
  email:             bheklilr2@gmail.com

github:
  repo: https://github.com/bheklilr/bheklilr.github.io

# Custom vars
version:             1.0.0
gems: [jekyll-paginate]
highlighter: rouge
